### PR TITLE
resource helper refactor

### PR DESCRIPTION
**Pull request by kirillseva**

### CODE REVIEW

**Comment by robertzk** [comment]
Thanks, looks great. Make sure to test extensively with any syberia projects you have on hand.

**Comment by peterhurford** [comment]
@robertzk @kirillseva Is it possible to add more automated tests as well?

**Comment by kirillseva** [comment]
@peterhurford no idea for now. We probably need a mock syberia project in testthat folder and do some stuff with it

**Comment by kirillseva** [comment]
Which is happening in another branch, the one with engines

**Comment by kirillseva** [comment]
Works on a local project @robertzk

**Comment by peterhurford** [comment]
@kirillseva Maybe merge this into that branch?  But since no one would really use this version yet, I guess that works for me.

**Comment by kirillseva** [comment]
@peterhurford I'm going to merge this into master of our common top secret project today

**Comment by kirillseva** [comment]
Oh, my bad. Yeah, the engines branch is not being used by anyone as far as I know

**Pull request merged**
